### ISSUE TITLE
Could not find a suitable MySQL module

### ISSUE THREAD

**Issue by efimka118** [FredyH/MySQLOO#140]
I've downloaded MySQLOO from releases page and drop it to garrysmod/lua/bin. Then i put `request('mysqloo')` in autorun, but error don't disappears. I'm running my server through VCS, WSL on linux, ubuntu. Also i'm tried to install tmysql4, but it's not changed anything. Also tried download x64 and x32, not working. I think modules just don't loading, but why? If you can help me i will be grateful to you, thanks in advance.

![image](https://github.com/user-attachments/assets/9a783b8a-2bf9-421d-a6d3-be20d67ee97b)

**Comment by FredyH** [comment]
Hi, you might have the incorrect version of MySQLOO (32 bit rather than 64 bit, or vice versa) or you placed it in the incorrect folder.
I can assure you that the module itself still loads correctly on all modern operating systems (I use it daily).
There is some potential that the library (mysqlite) that you are using is broken, but it is not related to this module.
