### ISSUE TITLE
requesting use of a convar to disable/enable the update check

### ISSUE THREAD

**Issue by VaasKahnGrim** [FredyH/MySQLOO#41]
Basically to prevent future annoying console spam getting dumped into a server's console

**Comment by FredyH** [comment]
The idea is to get people to upgrade to the latest version as fast as possible so developers can make use of the latest features, so it being annoying is exactly the way to achieve that.

Since there probably won't be a major new version of this library any time soon I don't think such a convar is necessary (the only reason there is a new version at all is because of x64).

Is there any particular reason you are not using the 9.6 release like crashes?

**Comment by VaasKahnGrim** [comment]
More just having only 1 addon that actually uses it so its just something I don't often check or bother with updating or thinking about. Ended up having the console spam making one of my servers tank a little bit before figuring out why. until then I was just going to ignore the thing entirely

**Comment by FredyH** [comment]
I don't see how a message every few minutes would tank a server?
