### ISSUE TITLE
attempt to index field 'MySQLDB' (a nil value)

### ISSUE THREAD

**Issue by SandeQ** [FredyH/MySQLOO#68]
I've just ran the x64 Linux server with the newest mysqloo, i'm not sure if it's related to the mysqloo, but i'm getting such error (At least it's not the SSL connection error o.O)

[libk] addons/libk/lua/libk/server/sv_libk_database.lua:293: attempt to index field 'MySQLDB' (a nil value)
  1. prepareForSQL - addons/libk/lua/libk/server/sv_libk_database.lua:293
   2. findAllDbByField - addons/libk/lua/libk/server/sv_libk_model.lua:241
    3. findByPlayer - addons/libk/lua/libk/server/sv_libk_model.lua:554
     4. fn - addons/libk/lua/libk/server/sv_libk_player.lua:3
      5. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109

[libk] addons/libk/lua/libk/server/sv_libk_database.lua:293: attempt to index field 'MySQLDB' (a nil value)
  1. prepareForSQL - addons/libk/lua/libk/server/sv_libk_database.lua:293
   2. findAllDbByField - addons/libk/lua/libk/server/sv_libk_model.lua:241
    3. findByPlayer - addons/libk/lua/libk/server/sv_libk_model.lua:554
     4. fn - addons/libk/lua/libk/server/sv_libk_player.lua:3
      5. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109

**Comment by Kefta** [comment]
That error doesn't really help, it's probably failing to connect somewhere but you've just posted the resulting Lua error from an external lib. If it's not printing a connection error, go into the source code and add some debug prints to see what's going on.

**Comment by viral32111** [comment]
The error helps a bit, it's saying that on line `293` of `addons/libk/lua/libk/server/sv_libk_database.lua` there's a variable named `MySQLDB` that's being used but is a nil value at the time.

I doubt it's a connection issue (despite that seeming very likely) else another Lua error from the module *should've* been printed to the console, calling the `:connect()` method doesn't return anything even on success. `MySQLDB` sounds like it should be storing the result of `mysqloo.connect(..)` which just returns a reference to an initalised database object, it does **not** connect until calling `:connect()`, in which case it should never be nil (see the documentation on the readme).

If `MySQLDB` is indeed the database object returned by `mysqloo.connect(...)` then the only way I can imagine that being nil **when initalised** is if the module failed to load and thus the `mysqloo.connect(...)` function was never set (but then that would output even more errors and the code might not even reach to where it did). But since this error caused by `MySQLDB` being nil **when referenced/called**, it's probabl something as simple as trying to access a variable outside of it's scope, thus it is undefined. 

I suspect what's happening is that the library's code is written for an older version of MySQLOO, and your upgrade has had some non-backwards compatible changes. (Although, I haven't been following too closely on code changes across versions, so I'm not too sure).

This can't really be solved by us unless you provide the source code to this library, if that isn't possible then you'll have to debug it yourself like Kefta said and simpply go step-by-step until you can fix the issue with the library.

**Comment by FredyH** [comment]
Could it not just be that the require("mysqloo") calls fails because some dependencies are missing? Have you put libmysqlclient next to the srcds executable? It might also be that openssl is missing on some servers.

**Comment by SandeQ** [comment]
My admin probably ran the 32 bit version of the server and got this error, so nvm with the nil value error, but i have another problem.

I've downloaded the x64 gmod linux server, put the gmsv_mysqloo_linux64.dll in garrysmod/lua/bin folder, and the libmysqlclient.so in the main folder, next to srcds files.

Now i'm getting such error

[LibK] FATAL: Couldn't load mysqloo, make sure it is correctly installed! errror was: Couldn't load module library!
MySQL Error: MySQLOO modules aren't installed properly!

What have i done wrong? I think i've placed the files in good folders, can it be something with LibK?

**Comment by viral32111** [comment]
`Couldn't load module library!` is a general Lua error that occurs when modules can't be found or loaded, so I doubt it is an issue with LibK.

Like what was said earlier, you may need OpenSSL libraries installed on the server along with the `libmysqlclient.so` lib, should be installable via `apt install openssl` as root (I dunno if `openssl-dev` is needed too). Although, I would've assumed OpenSSL would be standard to ship with every major OS these days.

**Comment by SandeQ** [comment]
Well, i have already installed the newest version of openssl, and i can't find openssl-dev o.O

**Comment by viral32111** [comment]
Is the `libmysqlclient.so` file compiled for x86-64/64-bit? You can find this out via the [`file`] command. It should say something like `ELF 64-bit LSB shared object` I think.

**Comment by SandeQ** [comment]
![image](https://user-images.githubusercontent.com/29819929/87141648-a9a76880-c2a3-11ea-9437-add82c6c5708.png)

**Comment by viral32111** [comment]
I'm really not sure then, from my experience it should work fine with everything you've done. Someone else is going have to help.

I'll download those beta releases for Linux and do some testing on a fresh stock machine to see if I can reproduce it, I'll get back to you if I find anything out.

**Comment by viral32111** [comment]
On a fresh Debian 10 machine with a stock x86-64 Garry's Mod server I was able to get it working by renaming the `libmysqlclient.so` to `libmysqlclient.so.21` (a symlink would also work just fine).

I realised this was the case when `ldd`'ing the `gmsv_mysqloo_linux64.dll` file, it was unable to find `libmysqlclient.so.21` because the one provided in the release is missing the `.21` suffix.

**Comment by SandeQ** [comment]
Closing, the answer up there solved the issue
