### ISSUE TITLE
Connection failed! SSL connection error: unknown error number

### ISSUE THREAD

**Issue by 20tps** [FredyH/MySQLOO#84]
**Issue:**
I made a fresh installation of Garrys Mod with DarkRP and DarkRP Modification Addon, on a virtual server within my dedicated server. I am fairly new to MySQL so I set up and installed phpMyAdmin to make things simpler. I'm not sure if I just made a dumb mistake when setting up everything or if it is an issue with MySQLOO.

**Versions:**
MySQL: `8.0.23`
MySQLOO: `9.6.1`
Server: `Ubuntu 20.04 x86_64`

**Error:**
```
Lua Error: gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:361: Connection failed! SSL connection error: unknown error number
Trying again in 5 seconds.
stack traceback:
        [C]: at 0xf15dfa00
        [C]: in function 'error'
        gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:361: in function <gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:357>
        [C]: in function 'v'
        lua/includes/modules/hook.lua:84: in function <lua/includes/modules/hook.lua:67>
```

_I know this isn't a help forum, but if it isn't a bug could I still get some assistance solving the issue?_

**Comment by FredyH** [comment]
This seems like it's probably because you are using MySQL 8 which is causing a lot of incompatibilities. In fact the oldest open issue also states this fact. The options you have right now seem to be to downgrade to MySQL 5 or 6 or to just disable SSL on the serverside (which might be unacceptable).

I am working on a new version that uses MariaDB's connector that includes SSL support and also some support for MySQL 8, in fact you can already try compiling that version yourself on the mariadb-connector branch. (although I am not sure if the 64 bit version works, the 32 bit version should.)
