### ISSUE TITLE
Operability of the new version on Linux

### ISSUE THREAD

**Issue by dok441** [FredyH/MySQLOO#94]
Hello, can you tell me for what reason Mysql version 9.6.1 can work, but starting from 9.7.0-beta-1, not one of the subsequent versions on Linux does not want to work. With 32-bit, it just writes that the module was not found. When 64-bit, crashes with the error Aborted (core dumped).
Testing on windows, there are no errors.
I use linux Ubuntu 13.10 64-bit

**Comment by FredyH** [comment]
I forgot to statically link libstdc++, which causes these issues on older distribution.
I uploaded updated versions to the same release of 9.7.0, simply redownload the dlls and it should work now, but please report whether or not it works now.

Nevertheless, you should really not be using Ubuntu 13.10, it is EOL since over 7 years.

**Comment by dok441** [comment]
Everything works, thank you for your advice and help.
